In [71]:
import pandas as pd
import numpy as np

In [72]:
vehicle = pd.read_csv('car_data.csv')

In [73]:
vehicle.head()

Vehicle_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0         ritz  2014           3.35           5.59       27000    Petrol   
1          sx4  2013           4.75           9.54       43000    Diesel   
2         ciaz  2017           7.25           9.85        6900    Petrol   
3      wagon r  2011           2.85           4.15        5200    Petrol   
4        swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [74]:
vehicle.shape

(301, 9)

In [75]:
vehicle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Vehicle_Name   301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [76]:
vehicle.isnull().sum()

Vehicle_Name     0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [77]:
print(vehicle.Fuel_Type.value_counts())

Petrol    239
Diesel     60
CNG         2
Name: Fuel_Type, dtype: int64


In [78]:
print(vehicle.Seller_Type.value_counts())

Dealer        195
Individual    106
Name: Seller_Type, dtype: int64


In [79]:
print(vehicle.Transmission.value_counts())

Manual       261
Automatic     40
Name: Transmission, dtype: int64


In [80]:
vehicle.replace({'Fuel_Type':{'Petrol':0, 'Diesel':1, 'CNG':2 }}, inplace=True)

In [81]:
vehicle.replace({'Seller_Type':{'Dealer':0, 'Individual':1 }}, inplace=True)

In [82]:
vehicle.replace({'Transmission':{'Manual':0, 'Automatic':1 }}, inplace=True)

In [83]:
vehicle.head()

Vehicle_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0         ritz  2014           3.35           5.59       27000          0   
1          sx4  2013           4.75           9.54       43000          1   
2         ciaz  2017           7.25           9.85        6900          0   
3      wagon r  2011           2.85           4.15        5200          0   
4        swift  2014           4.60           6.87       42450          1   

   Seller_Type  Transmission  Owner  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0

In [84]:
vehicle.describe()

Year  Selling_Price  Present_Price     Kms_Driven   Fuel_Type  \
count   301.000000     301.000000     301.000000     301.000000  301.000000   
mean   2013.627907       4.661296       7.628472   36947.205980    0.212625   
std       2.891554       5.082812       8.644115   38886.883882    0.425801   
min    2003.000000       0.100000       0.320000     500.000000    0.000000   
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000   
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000   
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000   
max    2018.000000      35.000000      92.600000  500000.000000    2.000000   

       Seller_Type  Transmission       Owner  
count   301.000000    301.000000  301.000000  
mean      0.352159      0.132890    0.043189  
std       0.478439      0.340021    0.247915  
min       0.000000      0.000000    0.000000  
25%       0.000000      0.000000    0.000000  
50%       0.000000      0.000000    0.000000  
75%       1.000000      0.000000    0.000000  
max       1.000000      1.000000    3.000000

In [85]:
X = vehicle.drop(['Selling_Price'], axis=1)
Y = vehicle['Selling_Price'] 

In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2 )

In [87]:
from sklearn.linear_model import LinearRegression

In [88]:
from sklearn.metrics import r2_score

In [89]:
from sklearn.preprocessing import OneHotEncoder

In [90]:
ohe = OneHotEncoder()
ohe.fit(X[['Vehicle_Name', 'Fuel_Type']])

OneHotEncoder()

In [91]:
from sklearn.compose import make_column_transformer

In [92]:
from sklearn.pipeline import make_pipeline

In [93]:
ohe.categories_

[array(['800', 'Activa 3g', 'Activa 4g', 'Bajaj  ct 100',
        'Bajaj Avenger 150', 'Bajaj Avenger 150 street',
        'Bajaj Avenger 220', 'Bajaj Avenger 220 dtsi',
        'Bajaj Avenger Street 220', 'Bajaj Discover 100',
        'Bajaj Discover 125', 'Bajaj Dominar 400', 'Bajaj Pulsar  NS 200',
        'Bajaj Pulsar 135 LS', 'Bajaj Pulsar 150', 'Bajaj Pulsar 220 F',
        'Bajaj Pulsar NS 200', 'Bajaj Pulsar RS200', 'Hero  CBZ Xtreme',
        'Hero  Ignitor Disc', 'Hero Extreme', 'Hero Glamour',
        'Hero Honda CBZ extreme', 'Hero Honda Passion Pro', 'Hero Hunk',
        'Hero Passion Pro', 'Hero Passion X pro', 'Hero Splender Plus',
        'Hero Splender iSmart', 'Hero Super Splendor', 'Honda Activa 125',
        'Honda Activa 4G', 'Honda CB Hornet 160R', 'Honda CB Shine',
        'Honda CB Trigger', 'Honda CB Unicorn', 'Honda CB twister',
        'Honda CBR 150', 'Honda Dream Yuga ', 'Honda Karizma',
        'Hyosung GT250R', 'KTM 390 Duke ', 'KTM RC200', 'KTM RC390',


In [94]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_),['Vehicle_Name', 'Fuel_Type']), remainder='passthrough')

In [95]:
lr = LinearRegression()

In [96]:
pipe = make_pipeline(column_trans, lr)

In [97]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['800', 'Activa 3g', 'Activa 4g', 'Bajaj  ct 100',
       'Bajaj Avenger 150', 'Bajaj Avenger 150 street',
       'Bajaj Avenger 220', 'Bajaj Avenger 220 dtsi',
       'Bajaj Avenger Street 220', 'Bajaj Discover 100',
       'Bajaj Discover 125', 'Bajaj Dominar 400', 'Baj...
       'corolla altis', 'creta', 'dzire', 'elantra', 'eon', 'ertiga',
       'etios cross', 'etios g', 'etios gd', 'etios liva', 'fortuner',
       'grand i10', 'i10', 'i20', 'ignis', 'innova', 'jazz',
       'land cruiser', 'omni', 'ritz', 's cross', 'swift', 'sx4', 'verna',
       'vitara brezza', 'wagon r', 'xcent'], dtype=object),
                                                                            array([0, 1, 2], dtype=int64)]),
                               

In [98]:
Y_pred = pipe.predict(X_test)

In [99]:
Y_pred

array([10.6484187 ,  2.22415583,  3.45479718,  3.85393136, 11.32644918,
        3.57508012,  1.36309646,  6.36215769, -0.26691394,  4.77279388,
        6.80507141,  5.27546688,  0.79101089,  8.9040801 ,  2.56534552,
        0.16752437,  1.21600656,  2.17781027, 11.7778757 ,  3.74155168,
        1.52093946,  9.3467826 ,  1.59507445,  9.90372703,  0.62129332,
        8.10677607,  1.72603257, -3.362575  ,  3.45643246,  3.0311519 ,
        0.37627968,  2.79955409,  6.28867739,  8.91604409, -3.17901509,
        6.18956093,  7.99376412,  5.90966729,  6.7724788 ,  5.50957942,
       18.80431241,  1.24573077,  0.99683454,  1.55272179,  5.50960348,
        7.76248355,  1.01152961,  6.20442304, 18.49367958,  2.66429023,
        8.0844829 , -2.42928754,  8.54998915,  1.14701228,  0.76279186,
       -1.47718354,  0.45865209,  8.27600376, -1.19161488, -3.37789995,
       12.88564777])

In [100]:
r2_score(Y_test, Y_pred)

0.8976152648661989

In [101]:
scores = []
for i in range(10):
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(X_train, Y_train)
    Y_pred = pipe.predict(X_test)
    scores.append(r2_score(Y_test, Y_pred))

In [104]:
np.argmax(scores)

0

In [105]:
scores[np.argmax(scores)]

0.95364332345531

In [106]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2, random_state=np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train, Y_train)
Y_pred = pipe.predict(X_test)
r2_score(Y_test, Y_pred)

0.95364332345531

In [107]:
import pickle

In [108]:
pickle.dump(pipe,open('LinearRegressionModel.pkl', 'wb'))

In [121]:
pipe.predict(pd.DataFrame([['KTM RC200', 2012, 6.5, 12345, 0, 0, 0, 0]], columns=['Vehicle_Name','Year','Present_Price','Kms_Driven','Fuel_Type','Seller_Type', 'Transmission', 'Owner']))

array([2.46550643])